steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA', '.']

 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA']
 
# Deploy container image to Cloud Run in the east region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui-us'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'us-east1'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'

# Deploy container image to Cloud Run in the APAC region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui-jp'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'asia-northeast1'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'

# Deploy container image to Cloud Run in the European region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui-eu'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'europe-west4'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'

#Regional options
#asia-east1 (Taiwan)
#asia-northeast1 (Tokyo)
#asia-northeast2 (Osaka)
#europe-north1 (Finland) leaf icon Low CO2
#europe-west1 (Belgium) leaf icon Low CO2
#europe-west4 (Netherlands)
#us-central1 (Iowa) leaf icon Low CO2
#us-east1 (South Carolina)
#us-east4 (Northern Virginia)
#us-west1 (Oregon) leaf icon Low CO2

 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'beta'
   - 'run'
   - 'domain-mappings' 
   - 'create' 
   - '--service' 
   - 'bitfoon-ui-us'
   - '--domain' 
   - 'us.bitfoon.com'
   - '--region'
   - 'us-east1'


options:
  logging: CLOUD_LOGGING_ONLY
