steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA', '.']

 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA']
 
# Deploy container image to Cloud Run in the east region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'us-east1'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'

# Deploy container image to Cloud Run in the APAC region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'asia-northeast1'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'

# Deploy container image to Cloud Run in the European region
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'bitfoon-ui'
   - '--image'
   - 'gcr.io/$PROJECT_ID/bitfoon-ui:$COMMIT_SHA'
   - '--region'
   - 'Netherlands'
   - '--port' 
   - '80'
   - '--allow-unauthenticated'


options:
  logging: CLOUD_LOGGING_ONLY
