steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/biftfoon/ui-image', '.']
options:
  logging: CLOUD_LOGGING_ONLY  

#Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/biftfoon/ui-image']
